package com.mercora.platform.common.exception;

public enum ErrorCode {

    VALIDATION_FAILED,
    RESOURCE_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    ACCESS_DENIED,
    UNAUTHORIZED,
    CONFLICT,

    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    TOKEN_NOT_FOUND,
    TOKEN_EXPIRED,

    PRODUCT_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    CATEGORY_ALREADY_EXISTS,
    OUT_OF_STOCK,

    CART_NOT_FOUND,
    CART_EMPTY,

    ORDER_NOT_FOUND,
    ORDER_ALREADY_CANCELLED,

    PAYMENT_NOT_FOUND,
    PAYMENT_FAILED,

    NOTIFICATION_FAILED

}
